name: bloc_analytics
description: Easy integrate you app with multiple analytics tracker, integrate with Firebase Analytics, Crashlytics and others
version: 0.6.0
author: guitcastro <guilherme.torres.castro@gmail.com>
homepage: https://github.com/guitcastro/dayrl_tracker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.0

dev_dependencies:
  lint: ^1.5.3
  mocktail: ^0.1.4
